version: "3.7"

services: 
    parsemarc:
        build:
            context: parsemarc/
            dockerfile: Dockerfile
        environment:
            - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
            - ELASTICSEARCH_SSL=False
            - ELASTICSEARCH_NUMBER_OF_SHARDS=1
            - ELASTICSEARCH_NUMBER_OF_REPLICAS=1
            - IMAP_HOST=imap.***.com
            - IMAP_USERNAME=***@***.com
            - IMAP_PASSWORD=***            
            - IMAP_PORT=993
        restart: always
    elasticsearch:
        image: elasticsearch:7.5.1
        environment: 
            - discovery.type=single-node
        ports: 
            - 9200:9200
            - 9300:9300
    kibana:
        image: kibana:7.5.1
        environment:
            - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
        ports:
            - 5601:5601