version: "3.7"

services: 
    parsedmarc:
        build:
            context: parsedmarc/
            dockerfile: Dockerfile
        environment:
            - DMARC_SAVE_AGGREGATE=True
            - DMARC_SAVE_FORENSIC=True
            - GEOIP_ACCOUNT_ID=***
            - GEOIP_LICENSE_KEY=***
            - GEOIP_EDITION_IDS=GeoLite2-ASN GeoLite2-City GeoLite2-Country
            - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
            - ELASTICSEARCH_SSL=False
            - ELASTICSEARCH_NUMBER_OF_SHARDS=1
            - ELASTICSEARCH_NUMBER_OF_REPLICAS=1
            - IMAP_HOST=imap.***.com
            - IMAP_USERNAME=***@***.com
            - IMAP_PASSWORD=***
            - IMAP_PORT=993
        restart: unless-stopped
        depends_on:
            - elasticsearch
    elasticsearch:
        image: elasticsearch:7.5.1
        environment: 
            - discovery.type=single-node
        ports: 
            - 9200:9200
            - 9300:9300
        restart: unless-stopped
    kibana:
        image: kibana:7.5.1
        environment:
            - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
        ports:
            - 5601:5601
        restart: unless-stopped
        depends_on:
            - elasticsearch
